### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by rajdeep26** [marchaos/flickr_retriever#1]
Running `node index.js` results in 

```
flickr_retriever/index.js:77
const processPhotosets = async (flickr, photosets) => {
                               ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by marchaos** [comment]
Hey, What version of node are you running? I assume you're on something before 7.6 when async/await was added. Try upgrading to 10 if you can.

**Comment by rajdeep26** [comment]
Yes. 6.9.5
