### ISSUE TITLE
ERR_STREM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by SimonThoustrup** [marchaos/flickr_retriever#2]
Hi

Script works great - thank you very much!
However from time to time it crashes with the following error. Restarting (including re-authorizing the app on the Flickr site via localhost:3000) allows the script to continue again for a while until the same error reappears.
Let me know if I can do anything to help.

events.js:177
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    at Transform.ondata (_stream_readable.js:713:22)
    at Transform.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Transform.Readable.push (_stream_readable.js:210:10)
    at Transform.push (_stream_transform.js:150:32)
    at Transform.afterTransform (_stream_transform.js:94:10)
    at Transform.transform [as _transform] (/root/flickr_retriever-master/node_modules/got/index.js:295:4)
Emitted 'error' event at:
    at PassThrough.<anonymous> (/root/flickr_retriever-master/node_modules/duplexer3/index.js:49:12)
    at PassThrough.emit (events.js:205:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at writeAfterEnd (_stream_writable.js:252:3)
    at PassThrough.Writable.write (_stream_writable.js:298:5)
    [... lines matching original stack trace ...]
    at Transform.Readable.push (_stream_readable.js:210:10)

**Comment by marchaos** [comment]
Hey, I have not seen this since using this script. What version of node are you using?

**Comment by SimonThoustrup** [comment]
Hey, I have node 12.4.0. I saw a different error just now that also made the script crash.

events.js:177
      throw er; // Unhandled 'error' event
      ^

GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/root/flickr_retriever-master/node_modules/got/index.js:482:24)
    at EventEmitter.emit (events.js:200:13)
    at getResponse (/root/flickr_retriever-master/node_modules/got/index.js:320:5)
    at Immediate.<anonymous> (/root/flickr_retriever-master/node_modules/got/index.js:147:6)
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event at:
    at EventEmitter.emit (events.js:200:13)
    at Immediate.<anonymous> (/root/flickr_retriever-master/node_modules/got/index.js:149:9)
    at processImmediate (internal/timers.js:439:21) {
  name: 'HTTPError',
  host: 'www.flickr.com',
  hostname: 'www.flickr.com',
  method: 'GET',
  path: '/photos/96318483@N04/10101111503/play/orig/6143c1189f/',
  protocol: 'https:',
  url: 'https://www.flickr.com/photos/96318483@N04/10101111503/play/orig/6143c1189f/',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    'content-type': 'text/html; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    date: 'Wed, 07 Aug 2019 14:01:49 GMT',
    server: 'Apache/2.4.39 (Ubuntu)',
    'set-cookie': [
      'xb=368013; expires=Sat, 04-Aug-2029 14:01:48 ' +
        'GMT; Max-Age=315360000; path=/; ' +
        'domain=.flickr.com',
      'localization=en-us%3Bdk%3Bdk; expires=Wed, 04-Aug-2021 ' +
        '14:01:48 GMT; Max-Age=62899200; path=/; ' +
        'domain=.flickr.com',
      'flrbp=1565186508-249e3d14893827de08b00350337e4bf512349d01; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbs=1565186508-a66666a42c8cd6a8a7bf69ac04af182e24ba1427; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbgrp=1565186508-b3dab3fdec1902b51ad3537ad3cb4e87cba4db27; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbgdrp=1565186508-66f13a74e03c132f2fb3f73c0d2aee2aa7866f0a; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbgmrp=1565186508-648c31b763520ec77bac8901877f4bf2ce826c57; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbcr=1565186508-042a2211c30588c061819f6b6153c657f4e96cfd; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbrst=1565186508-6aa8106b8ccb63587fa1d4f1aafb6bcb47d5ee62; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrtags=1565186508-782fcb70ecacc537dfc9cb5927edbc28e3711c48; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbrp=1565186508-dc1f65458d70e424c23ef71c8578ace4a8ba0af6; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrbrgs=1565186508-77cf225a0d345291a0a3e62337940afa587c9dbb; ' +
        'expires=Mon, 03-Feb-2020 14:01:48 GMT; ' +
        'Max-Age=15552000; path=/; domain=.flickr.com; ' +
        'httponly',
      'flrb=41; expires=Wed, 07-Aug-2019 15:01:48 GMT; ' +
        'Max-Age=3600; path=/; domain=.flickr.com; ' +
        'httponly'
    ],
    'content-security-policy': "style-src 'unsafe-inline' https://*.flickr.com " +
      'https://*.staticflickr.com https://*.flickr.net ' +
      'https://*.braintreegateway.com https://*.kaptcha.com ' +
      'https://*.paypal.com http://api.flickr.com https://*.pinterest.com ' +
      'https://connect.facebook.net https://*.facebook.com ' +
      'https://*.maps.api.here.com https://*.maps.cit.api.here.com ' +
      'https://cdn.siftscience.com https://tpc.googlesyndication.com; ' +
      'default-src https://*.flickr.com https://*.staticflickr.com ' +
      'https://*.flickr.net https://*.braintreegateway.com ' +
      'https://*.kaptcha.com https://*.paypal.com http://api.flickr.com ' +
      'https://*.pinterest.com https://connect.facebook.net ' +
      'https://*.facebook.com https://*.maps.api.here.com ' +
      'https://*.maps.cit.api.here.com https://cdn.siftscience.com ' +
      'https://tpc.googlesyndication.com; img-src data: blob: ' +
      'https://*.flickr.com https://*.flickr.net http://*.flickr.net ' +
      'https://*.staticflickr.com http://*.staticflickr.com https://*.yimg.com ' +
      'https://*.yahoo.com https://image.maps.api.here.com ' +
      'https://*.paypal.com https://*.pinterest.com ' +
      'http://*.static-alpha.flickr.com https://connect.facebook.net ' +
      'https://*.facebook.com https://*.maps.api.here.com ' +
      'https://*.maps.cit.api.here.com https://creativecommons.org ' +
      'https://hexagon-analytics.com https://*.2o7.net; media-src ' +
      'https://*.flickr.com https://*.flickr.net http://*.flickr.net ' +
      'https://*.staticflickr.com https://*.yahoo.com; script-src ' +
      "'unsafe-inline' 'unsafe-eval' 'nonce-8293a0df6e9842554dcd03d8beeb6245' " +
      'https://*.flickr.com http://*.flickr.net https://*.flickr.net ' +
      'https://*.staticflickr.com https://*.analytics.yahoo.com ' +
      'https://yep.video.yahoo.com https://video.media.yql.yahoo.com ' +
      'https://*.yahooapis.com https://*.braintreegateway.com ' +
      'https://*.paypalobjects.com https://connect.facebook.net ' +
      'https://*.facebook.com https://*.maps.api.here.com ' +
      'https://*.maps.cit.api.here.com https://cdn.siftscience.com ' +
      'https://assets.adobedtm.com https://securepubads.g.doubleclick.net ' +
      'https://adservice.google.com; connect-src https://*.flickr.com ' +
      'https://*.flickr.net http://*.flickr.net https://*.staticflickr.com ' +
      'https://geo.query.yahoo.com https://*.yahooapis.com ' +
      'http://api.flickr.com https://*.pinterest.com http://*.yahoo.com ' +
      'https://*.maps.api.here.com https://*.maps.cit.api.here.com ' +
      'https://cdn.siftscience.com https://*.demdex.net ' +
      'https://securepubads.g.doubleclick.net; frame-ancestors ' +
      'https://*.flickr.com; report-uri ' +
      'https://csp.flickr.com/beacon/csp?src=adsecflickr;',
    'x-frame-options': 'SAMEORIGIN',
    'content-encoding': 'gzip',
    'x-cache': 'Error from cloudfront',
    via: '1.1 76ab02fad35a55e39b30639d4e6784bc.cloudfront.net (CloudFront)',
    'x-amz-cf-pop': 'CPH50-C1',
    'x-amz-cf-id': 'P8525vts_lI7tOMDYEQbuxEZ4N78jRaw0xAQpNIdmh6guX5iKMS6VQ=='
  }
}
